<div class="text packagelable">
	<span>
		Name:
	</span>
	<span class="packagedata packagetext">
		<input type="text" name="Name" size="15" />
	</span>
	<span>
		<label name="Nm"></label>
	</span>

</div>		
				
<div class="text packagelable">
	<span>
		Address:
	</span>

	<span class="packagedata packagetext">
		<input type="text" name="Address" size="15" />
	</span>
</div>
				
<div class="text packagelable">
	<span>
		Ph.No:
	</span>
	<span class="packagedata packagetext">
		<input type="text" name="Ph_No" size="15" />
	</span>
</div>
				
<div class="text packagelable">
	<span>
		Email:
	</span>
	<span class="packagedata packagetext">
		<input type="text" name="Email" size="15" />
	</span>
</div>			

<div class="text packagelable">
	<span >
		Packages:
	</span>
	<span class="packagedata packagetext">			
		Package Id
	</span>
	<span class="packagedata packagetype">
		Types
	</span>
	<span class="packagedata packagerate">
		Rate
	</span>
	<span class="packagedata packagenot">
		How many times you want to select:
	</span>
</div>