	<div id="nav">
		<li>
			Information
		</li>
	
		<li>
			<a href="Home.php" id=obj4>Home</a>
		</li>
	
		<li>
			<a href="AboutUs.php" >About Us</a>
		</li>

		<li>
			<a href="IndianTour.php" >Indian Tour</a>
		</li>
	
		<li>
			<a href="BookingYourTour.php" >Booking Your Tour</a>
		</li>

		<li>		
			<a href="ContactUS.php" >Contact US</a>
		</li>

		<li class="navhead head">
			Information Travel
		</li>		
	</div>